# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# Features:
# - Check build and dependencies
# - Check Unit Tests

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore InfoTrackBooking/InfoTrackBooking.sln
      - name: Build
        run: dotnet build InfoTrackBooking/InfoTrackBooking.csproj
      - name: Run automated unit and integration tests
        run: dotnet test Tests/Tests.csproj /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        with:
          workspace: App/App/App.csproj
          implicit-restore: true
